FABJ-536 Add support for mutual TLS when connecting to CA
hyperledger/fabric-sdk-java pull request #81
Opened 2020-09-21 22:31 UTC by TsvetanG

2020-09-30 14:41 UTC, bestbeforetoday requested changes
This needs to have accompanying tests; ideally both unit tests (where practical) and certainly used in integration tests

2020-09-30 14:41 UTC, bestbeforetoday commented on src/main/java/org/hyperledger/fabric_ca/sdk/HFCAClient.java
> +                    Certificate tlsCleintCertificate = new CryptoPrimitives().bytesToCertificate(tlsClientCertAsBytes);
I'm being very picky but it's worth getting it right... `tlsCleintCertificate` should be `tlsClientCertificate`

2020-10-09 14:00 UTC, bestbeforetoday requested changes

2020-10-09 14:01 UTC, bestbeforetoday commented
I know I'm raising lots of comments but thank you for taking the time to submit these changes. We appreciate it!

2020-10-26 17:35 UTC, TsvetanG commented
@bestbeforetoday Thank you for the feedback and comments! I have addressed all of them. Any further comments are welcome!
As my team is using HLF 2.2 we will need this change to be incorporated in 2.2.x branch. Let me know if I can help to make that happen.

Best Regards,
Tsvetan
PS: Apology for the delay!

2020-10-27 15:29 UTC, bestbeforetoday approved these changes

2020-10-27 15:35 UTC, bestbeforetoday commented
The changes look good to me but they won't merge as-is since the base branch has changed. It needs to be rebased on top of the current branch state.

Feel free to cherry-pick this change to both `release-2.2` and `master` branches and submit PRs for those changes too. Otherwise I should be able to do the cherry-pick on your behalf. If your intended target is only the `release-2.2` branch then you could submit a PR for only `master` and `release-2.2` branches (preferably `master` first) and leave `release-1.4` as-is.

2020-11-04 23:34 UTC, yzhivkov commented
Pushed one more commit so that the code is streamlined with master. For some reason one of the tests is failing but does not seem to be caused by the changes in this PR. Is there any way we can trigger a rebuild?

2020-11-05 06:50 UTC, bestbeforetoday commented
/azp run

2020-11-05 13:33 UTC, bestbeforetoday approved these changes

2020-11-05 13:35 UTC, bestbeforetoday commented
This PR is out of date with the current release-1.4 branch so needs to be rebased on release-1.4 before merging.

2020-11-11 15:33 UTC, merged