FABJ-539: loaded policy yaml file and close IO stream.
hyperledger/fabric-sdk-java pull request #82
Opened 2020-09-30 03:51 UTC by JiangCN

Signed-off-by: 3htj <1786951843@qq.com>

2020-09-30 12:27 UTC, bestbeforetoday requested changes

2020-09-30 12:27 UTC, bestbeforetoday commented on src/main/java/org/hyperledger/fabric/sdk/ChaincodeEndorsementPolicy.java
> +        FileInputStream policyFileStream = new FileInputStream(yamlPolicyFile);
Could you use try-with-resources to ensure the close is called?
https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html

2020-09-30 12:27 UTC, bestbeforetoday commented on src/main/java/org/hyperledger/fabric/sdk/ChaincodeEndorsementPolicy.java
> +        FileInputStream policyFileStream = new FileInputStream(yamlPolicyFile.toFile());
As above, please use try-with-resources

2020-10-09 03:07 UTC, JiangCN commented
The test can not past. But i did not modifiy there.

2020-10-09 08:09 UTC, bestbeforetoday commented
A chaincode change highlighted a bad dependency in the test chaincode used by the SDK integration tests. I have a PR with a fix so I'll kick this build off again once that's in.

2020-10-09 12:24 UTC, bestbeforetoday commented
The try-with-resources deals with closing the stream so the code does not need to do it explicitly. The try-block shouldn't be larger than necessary, so should just enclose the lines that use the stream, not all the code in the method.

To save time, I've made a similar change and removed the duplication of code between the two methods in PR #85 so this PR is no longer required.

Thank you for raising the issue and taking the time to submit a pull request with a candidate fix.

2020-10-09 12:24 UTC, closed without merging